In [94]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split

In [4]:
transformer = joblib.load("../modelos/pipelines/pipelines1.joblib")

In [7]:
transformer.transform([['male', 46, 2000,'own']])

c:\users\diana\onedrive\mia\dsi02\modelocredito\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
c:\users\diana\onedrive\mia\dsi02\modelocredito\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[0.48214286, 0.09629141, 0.        , 1.        , 0.        ,
        1.        , 0.        ]])

In [11]:
df = pd.read_csv("../data/german_credit_data.csv")

In [24]:
train, test = train_test_split(df, test_size=0.3, random_state=42)

In [25]:
features = ['Sex','Age','Credit amount', 'Housing']
y_train = (train['Risk']=='bad').astype('int') #convierte a binario 1 malos, 0 buenos
x_train = train[features]
x_train_transformed = transformer.transform(x_train)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

In [62]:
Results= cross_validate(LogisticRegression(),x_train_transformed, y_train, cv=5, return_train_score=True, scoring=["accuracy"])
#resumen de resultados del modelo, muestra los resultados de los entrenamientos
Results

{'fit_time': array([0.00800705, 0.00480914, 0.00697708, 0.00498867, 0.00498557]),
 'score_time': array([0.        , 0.        , 0.00101662, 0.        , 0.00096416]),
 'test_accuracy': array([0.70714286, 0.69285714, 0.67857143, 0.72142857, 0.70714286]),
 'train_accuracy': array([0.70178571, 0.70535714, 0.70892857, 0.69821429, 0.70178571])}

In [63]:
print("{} +- {}".format(Results['train_accuracy'].mean(),Results['train_accuracy'].std()))
print("{} +- {}".format(Results['test_accuracy'].mean(),Results['test_accuracy'].std()))

0.7032142857142857 +- 0.0036421567954234525
0.7014285714285714 +- 0.014568627181693668


In [29]:
clf = LogisticRegression()
clf.fit(x_train_transformed, y_train)

LogisticRegression()

In [31]:
clf.predict(transformer.transform([['male',46, 2000,'own']]))

c:\users\diana\onedrive\mia\dsi02\modelocredito\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
c:\users\diana\onedrive\mia\dsi02\modelocredito\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0])

In [33]:
clf.predict_proba(transformer.transform([['male',46, 2000,'own']]))

c:\users\diana\onedrive\mia\dsi02\modelocredito\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
c:\users\diana\onedrive\mia\dsi02\modelocredito\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[0.83685017, 0.16314983]])

In [80]:
predict = clf.predict_proba(x_train_transformed)#[:1]
predict

array([[0.73513533, 0.26486467],
       [0.80865055, 0.19134945],
       [0.74097874, 0.25902126],
       ...,
       [0.68087674, 0.31912326],
       [0.74425004, 0.25574996],
       [0.667567  , 0.332433  ]])

In [38]:
y_train

541    0
440    0
482    0
422    0
778    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Risk, Length: 700, dtype: int32

In [91]:
tabla = []
for i in range (700):
    tabla.append([predict[i][1], y_train.values[i]])

In [92]:
tabla

[[0.26486467162635713, 0],
 [0.19134945407205287, 0],
 [0.25902126476486487, 0],
 [0.1476745679302906, 0],
 [0.25243051620987617, 0],
 [0.2572357247078429, 1],
 [0.399040729801494, 1],
 [0.3511452833000528, 0],
 [0.349820488684946, 0],
 [0.22502384442628115, 0],
 [0.18016557743268843, 1],
 [0.23068052172309803, 0],
 [0.16433156845002522, 0],
 [0.45611400924154094, 1],
 [0.17408979420937915, 0],
 [0.22134183097438076, 0],
 [0.27260839932217285, 1],
 [0.21459707016857893, 0],
 [0.2950723883251272, 1],
 [0.18688311237193084, 1],
 [0.31418949280078795, 0],
 [0.30495115825770885, 0],
 [0.19322952968931945, 1],
 [0.23687251769003173, 0],
 [0.3760284398996412, 0],
 [0.21191893096830688, 0],
 [0.36722003381590657, 0],
 [0.1503901649414198, 1],
 [0.5060401999801326, 1],
 [0.3437101455657979, 0],
 [0.19052060833190185, 0],
 [0.32637493241831406, 0],
 [0.3380605261026293, 1],
 [0.11896739426593628, 0],
 [0.08975009831590866, 0],
 [0.1805678023332904, 0],
 [0.3529611631419685, 1],
 [0.219945794402

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [64]:
Results= cross_validate(KNeighborsClassifier(n_neighbors=35),x_train_transformed, y_train, cv=5, return_train_score=True, scoring=["accuracy"])
print("{} +- {}".format(Results['train_accuracy'].mean(),Results['train_accuracy'].std()))
print("{} +- {}".format(Results['test_accuracy'].mean(),Results['test_accuracy'].std()))

0.7053571428571429 +- 0.006487822187351794
0.687142857142857 +- 0.02490799396308955


In [58]:
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [66]:
Results= cross_validate(DecisionTreeClassifier(max_depth=3),x_train_transformed, y_train, cv=5, return_train_score=True, scoring=["accuracy"])
print("{} +- {}".format(Results['train_accuracy'].mean(),Results['train_accuracy'].std()))
print("{} +- {}".format(Results['test_accuracy'].mean(),Results['test_accuracy'].std()))

0.7278571428571429 +- 0.005486532677049025
0.7014285714285714 +- 0.016536909861128886


In [69]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
Results= cross_validate(RandomForestClassifier(n_estimators=100, max_depth=3),x_train_transformed, y_train, cv=5, return_train_score=True, scoring=["accuracy"])
print("{} +- {}".format(Results['train_accuracy'].mean(),Results['train_accuracy'].std()))
print("{} +- {}".format(Results['test_accuracy'].mean(),Results['test_accuracy'].std()))

0.7242857142857143 +- 0.003846546290810347
0.6985714285714286 +- 0.010497813183356491


In [73]:
from sklearn.svm import SVC

In [93]:
Results= cross_validate(SVC(kernel='linear'),x_train_transformed, y_train, cv=5, return_train_score=True, scoring=["accuracy"])
print("{} +- {}".format(Results['train_accuracy'].mean(),Results['train_accuracy'].std()))
print("{} +- {}".format(Results['test_accuracy'].mean(),Results['test_accuracy'].std()))

0.7014285714285714 +- 0.0007142857142857119
0.7014285714285714 +- 0.002857142857142891


In [96]:
def ks(data=None,target=None, prob=None):
    data['target0'] = 1 - data[target]
    data['bucket'] = pd.qcut(data[prob], 10)
    grouped = data.groupby('bucket', as_index = False)
    kstable = pd.DataFrame()
    kstable['min_prob'] = grouped.min()[prob]
    kstable['max_prob'] = grouped.max()[prob]
    kstable['events']   = grouped.sum()[target]
    kstable['nonevents'] = grouped.sum()['target0']
    kstable = kstable.sort_values(by="min_prob", ascending=False).reset_index(drop = True)
    kstable['event_rate'] = (kstable.events / data[target].sum()).apply('{0:.2%}'.format)
    kstable['nonevent_rate'] = (kstable.nonevents / data['target0'].sum()).apply('{0:.2%}'.format)
    kstable['cum_eventrate']=(kstable.events / data[target].sum()).cumsum()
    kstable['cum_noneventrate']=(kstable.nonevents / data['target0'].sum()).cumsum()
    kstable['KS'] = np.round(kstable['cum_eventrate']-kstable['cum_noneventrate'], 3) * 100

    #Formating
    kstable['cum_eventrate']= kstable['cum_eventrate'].apply('{0:.2%}'.format)
    kstable['cum_noneventrate']= kstable['cum_noneventrate'].apply('{0:.2%}'.format)
    kstable.index = range(1,11)
    kstable.index.rename('Decile', inplace=True)
    pd.set_option('display.max_columns', 9)
    print(kstable)
    
    #Display KS
    from colorama import Fore
    print(Fore.RED + "KS is " + str(max(kstable['KS']))+"%"+ " at decile " + str((kstable.index[kstable['KS']==max(kstable['KS'])][0])))
    return(kstable)

In [170]:
tab1=pd.DataFrame(tabla, columns=['Probabilidad', 'Resultado'])

In [176]:
tab1.head()

Probabilidad  Resultado
0      0.264865          0
1      0.191349          0
2      0.259021          0
3      0.147675          0
4      0.252431          0

In [179]:
tab1['Probabilidad']

0      0.264865
1      0.191349
2      0.259021
3      0.147675
4      0.252431
         ...   
695    0.259024
696    0.236623
697    0.319123
698    0.255750
699    0.332433
Name: Probabilidad, Length: 700, dtype: float64

In [182]:
mydf = ks(data=tab1,target="Resultado", prob="Probabilidad")

        min_prob  max_prob  events  nonevents event_rate nonevent_rate  \
Decile                                                                   
1       0.458679  0.681389      38         32     18.18%         6.52%   
2       0.391072  0.457377      33         37     15.79%         7.54%   
3       0.347557  0.390945      29         41     13.88%         8.35%   
4       0.306771  0.346207      16         54      7.66%        11.00%   
5       0.273525  0.305206      28         42     13.40%         8.55%   
6       0.250303  0.273323      18         52      8.61%        10.59%   
7       0.231471  0.249871      13         57      6.22%        11.61%   
8       0.209716  0.231132       9         61      4.31%        12.42%   
9       0.171178  0.209380      18         52      8.61%        10.59%   
10      0.075215  0.170660       7         63      3.35%        12.83%   

       cum_eventrate cum_noneventrate    KS  
Decile                                       
1             18.18